language: python

python:
  - 3.6.1

services: postgresql
cache: pip

before_install:
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
  - pip install psycopg2 --quiet

before_script:
  - cp environment_example.py environment.py
  - psql -c "CREATE DATABASE travisci;" -U postgres

script:
  - python manage.py migrate --noinput
  - coverage run --source='.' manage.py test

notifications:
  email:
    on_success: never
    on_failure: always

after_success:
    - coveralls
