version: '3'
services:

  bot:
    image: bsquidwrd/livebot:latest
    restart: unless-stopped
    env_file:
      - dev.env
    command: ["python", "bot.py"]
    networks:
      - default
      - backend

  update_users:
    image: bsquidwrd/livebot:latest
    restart: unless-stopped
    env_file:
      - dev.env
    command: ["python", "update_users.py"]
    networks:
      - default
      - backend

  website:
    image: bsquidwrd/livebot:latest
    restart: unless-stopped
    ports:
      - "8000:80"
    env_file:
      - dev.env
    command: ["python", "manage.py", "runserver", "0.0.0.0:80"]
    networks:
      - default
      - backend

networks:
  backend:
    internal: true
