# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 05:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordChannel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Channel ID')),
                ('name', models.CharField(max_length=255, verbose_name='Channel Name')),
            ],
            options={
                'verbose_name': 'Discord Channel',
                'verbose_name_plural': 'Discord Channels',
            },
        ),
        migrations.CreateModel(
            name='DiscordMessage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Message ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.TextField()),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livebot.DiscordChannel')),
            ],
            options={
                'verbose_name': 'Discord Message',
                'verbose_name_plural': 'Discord Messages',
            },
        ),
        migrations.CreateModel(
            name='DiscordServer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Server ID')),
                ('name', models.CharField(max_length=255, verbose_name='Server Name')),
            ],
            options={
                'verbose_name': 'Discord Server',
                'verbose_name_plural': 'Discord Servers',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('message_token', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.TextField(default='')),
                ('email', models.BooleanField(default=False)),
                ('subject', models.CharField(blank=True, default=None, max_length=4000, null=True)),
                ('body', models.CharField(blank=True, default=None, max_length=4000, null=True)),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='livebot.DiscordChannel', verbose_name='Discord Message')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livebot.Log', verbose_name='Log Item')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
            },
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Tweet ID')),
                ('message', models.CharField(max_length=140, verbose_name='Tweet Message')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Tweet',
                'verbose_name_plural': 'Tweets',
            },
        ),
        migrations.CreateModel(
            name='TwitchChannel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Channel ID')),
                ('name', models.CharField(max_length=255, verbose_name='Channel Name')),
            ],
            options={
                'verbose_name': 'Twitch Channel',
                'verbose_name_plural': 'Twitch Channels',
            },
        ),
        migrations.CreateModel(
            name='TwitchNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('twitch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livebot.TwitchChannel', verbose_name='Twitch Channel')),
            ],
            options={
                'verbose_name': 'Twitch Channel',
                'verbose_name_plural': 'Twitch Channels',
            },
        ),
        migrations.CreateModel(
            name='Twitter',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Twitter ID')),
                ('name', models.CharField(max_length=255, verbose_name='Username')),
            ],
            options={
                'verbose_name': 'Twitter Account',
                'verbose_name_plural': 'Twitter Accounts',
            },
        ),
        migrations.AddField(
            model_name='tweet',
            name='twitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livebot.Twitter', verbose_name='Twitter Account'),
        ),
        migrations.AddField(
            model_name='notification',
            name='tweet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='livebot.Tweet', verbose_name='Twitter Message'),
        ),
        migrations.AddField(
            model_name='notification',
            name='twitch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livebot.TwitchChannel', verbose_name='Twitch Channel'),
        ),
        migrations.AddField(
            model_name='discordchannel',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livebot.DiscordServer', verbose_name='Channel Server'),
        ),
    ]
