# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 05:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livebot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='twitchnotification',
            options={'verbose_name': 'Twitch Noticication', 'verbose_name_plural': 'Twitch Noticications'},
        ),
    ]
