# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 06:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('livebot', '0002_auto_20170729_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitchnotification',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
