# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 19:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livebot', '0004_auto_20170730_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitchnotification',
            name='success',
        ),
        migrations.RemoveField(
            model_name='twitchnotification',
            name='timestamp',
        ),
    ]
