# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 00:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('livebot', '0006_auto_20170730_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitchLive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('twitch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livebot.TwitchChannel', verbose_name='Twitch Channel')),
            ],
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Noticication', 'verbose_name_plural': 'Noticications'},
        ),
        migrations.AlterModelOptions(
            name='twitchnotification',
            options={'verbose_name': 'Twitch Notification', 'verbose_name_plural': 'Twitch Notifications'},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='discord_message',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='tweet',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='twitch',
        ),
        migrations.AddField(
            model_name='notification',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='live',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='livebot.TwitchLive', verbose_name='Twitch Live'),
            preserve_default=False,
        ),
    ]
