# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livebot', '0008_auto_20170731_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitchnotification',
            name='message',
            field=models.CharField(blank=True, default="I'm Live! {url}", max_length=255, null=True, verbose_name='Notification Message'),
        ),
    ]
