# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livebot', '0010_auto_20170731_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitchnotification',
            name='message',
            field=models.CharField(default='{name} is Live! {url}', max_length=255, verbose_name='Notification Message'),
        ),
    ]
