# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livebot', '0013_auto_20170801_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordchannel',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Channel ID'),
        ),
        migrations.AlterField(
            model_name='discordserver',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Server ID'),
        ),
        migrations.AlterField(
            model_name='twitchchannel',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Channel ID'),
        ),
        migrations.AlterField(
            model_name='twitter',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Twitter ID'),
        ),
    ]
