# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livebot', '0014_auto_20170802_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='object_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='twitchnotification',
            name='object_id',
            field=models.BigIntegerField(),
        ),
    ]
