# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livebot', '0015_auto_20170802_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitchnotification',
            name='message',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Notification Message'),
        ),
    ]
