# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livebot', '0018_auto_20170813_2125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discordchannel',
            options={'ordering': ['guild__name', 'name'], 'verbose_name': 'Discord Channel', 'verbose_name_plural': 'Discord Channels'},
        ),
        migrations.AlterModelOptions(
            name='discordguild',
            options={'ordering': ['name'], 'verbose_name': 'Discord Guild', 'verbose_name_plural': 'Discord Guilds'},
        ),
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Log', 'verbose_name_plural': 'Logs'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-live__timestamp'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterModelOptions(
            name='twitchlive',
            options={'ordering': ['-timestamp', 'twitch__name'], 'verbose_name': 'Twitch Live', 'verbose_name_plural': 'Twitch Live Instances'},
        ),
        migrations.AlterModelOptions(
            name='twitter',
            options={'ordering': ['name'], 'verbose_name': 'Twitter Account', 'verbose_name_plural': 'Twitter Accounts'},
        ),
    ]
