# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 18:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livebot', '0019_auto_20170818_0801'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='twitchchannel',
            options={'ordering': ['name'], 'verbose_name': 'Twitch Channel', 'verbose_name_plural': 'Twitch Channels'},
        ),
    ]
