# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-16 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livebot', '0020_auto_20170819_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Stream Title')),
                ('language', models.CharField(blank=True, max_length=50, null=True, verbose_name='Language')),
                ('game_id', models.IntegerField(verbose_name='Game ID')),
                ('type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Webhook Type')),
                ('viewer_count', models.IntegerField(blank=True, null=True, verbose_name='Viewer Count')),
                ('live', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livebot.TwitchLive', verbose_name='Twitch Live')),
            ],
            options={
                'verbose_name': 'Webhook Notification',
                'verbose_name_plural': 'Webhook Notifications',
                'ordering': ['-live__timestamp'],
            },
        ),
    ]
