# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-16 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livebot', '0021_webhooknotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhooknotification',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Notification Type'),
        ),
    ]
