# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-16 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livebot', '0022_auto_20171216_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhooknotification',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Webhook ID'),
        ),
    ]
