# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-16 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('livebot', '0024_auto_20171216_1239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webhooknotification',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Webhook Notification', 'verbose_name_plural': 'Webhook Notifications'},
        ),
        migrations.AddField(
            model_name='webhooknotification',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
