# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-20 03:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livebot', '0025_auto_20171216_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webhooknotification',
            name='twitch',
        ),
        migrations.DeleteModel(
            name='WebhookNotification',
        ),
    ]
