# Generated by Django 2.0 on 2017-12-24 18:58

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.query_utils


class Migration(migrations.Migration):

    dependencies = [
        ('livebot', '0026_auto_20171219_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=django.db.models.query_utils.Q(app_label='livebot'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='twitchnotification',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=django.db.models.query_utils.Q(app_label='livebot'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
