# Generated by Django 2.0 on 2018-02-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livebot', '0027_auto_20171224_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitchchannel',
            name='display_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Channel Display Name'),
        ),
    ]
