# Generated by Django 2.0 on 2018-02-21 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livebot', '0028_twitchchannel_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitchchannel',
            name='offline_image',
            field=models.URLField(blank=True, null=True, verbose_name='Offline Image URL'),
        ),
        migrations.AddField(
            model_name='twitchchannel',
            name='profile_image',
            field=models.URLField(blank=True, null=True, verbose_name='Profile Image URL'),
        ),
    ]
