# Generated by Django 2.0 on 2018-02-22 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livebot', '0029_auto_20180221_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitchGame',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Game ID')),
                ('name', models.CharField(max_length=255, verbose_name='Game Name')),
                ('box_art', models.URLField(blank=True, null=True, verbose_name='Game Box Art')),
            ],
        ),
    ]
