# Generated by Django 2.0 on 2018-02-22 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livebot', '0030_twitchgame'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='twitchgame',
            options={'verbose_name': 'Twitch Game', 'verbose_name_plural': 'Twitch Games'},
        ),
    ]
