# Generated by Django 2.0 on 2018-02-22 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livebot', '0031_auto_20180222_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitchgame',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Game Name'),
        ),
    ]
