# Generated by Django 2.0 on 2018-05-19 17:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('livebot', '0032_auto_20180222_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='BearerToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp')),
                ('expired', models.BooleanField(default=False, verbose_name='Expired')),
                ('access_token', models.CharField(max_length=255, verbose_name='Access Token')),
                ('expires_in', models.BigIntegerField(verbose_name='Expires In (seconds)')),
                ('refresh_token', models.CharField(max_length=255, verbose_name='Refresh Token')),
            ],
            options={
                'verbose_name': 'Bearer Token',
                'verbose_name_plural': 'Bearer Tokens',
                'ordering': ['-timestamp', 'expired'],
            },
        ),
    ]
