# Generated by Django 2.0 on 2018-09-22 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livebot', '0033_bearertoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitchnotification',
            name='delay_minutes',
            field=models.IntegerField(default=60, verbose_name='Delay Minutes'),
        ),
    ]
