# Generated by Django 2.2.3 on 2019-07-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livebot', '0035_twitchlive_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitchgame',
            name='name',
            field=models.TextField(blank=True, default='', max_length=255, verbose_name='Game Name'),
        ),
    ]
